import TrainingConfigIcon from '@/assets/icons/TrainingConfig.png'
import MovementConfigIcon from '@/assets/icons/MovementConfig.png'
import PerceptionConfigIcon from '@/assets/icons/PerceptionConfig.png'
import NavigationRewardIcon from '@/assets/icons/NavigationReward.png'
import AdvancedNavRewardIcon from '@/assets/icons/AdvancedNavReward.png'
import TurnInPlateIcon from '@/assets/icons/TurnInPlate.png'

export const navigationParamGroups = [
  {
    id: 'basic',
    name: '基础训练配置',
    icon: TrainingConfigIcon,
    count: 5,
    params: [
      {
        key: 'total_timesteps',
        label: '总训练步数',
        type: 'number',
        defaultValue: 1500000,
        step: 1000,
        min: 1000,
        description: '训练的总步数，影响训练时长和最终效果',
      },
      {
        key: 'learning_rate',
        label: '学习率',
        type: 'number',
        defaultValue: 0.0001,
        step: 0.00001,
        min: 0.000001,
        max: 0.01,
        description: '控制模型参数更新的速度',
      },
      {
        key: 'batch_size',
        label: '批次大小',
        type: 'number',
        defaultValue: 1024,
        step: 32,
        min: 32,
        max: 4096,
        description: '每次训练使用的样本数量',
      },
      {
        key: 'use_gpu',
        label: '使用GPU',
        type: 'checkbox',
        defaultValue: true,
        description: '是否使用GPU加速训练',
        checkboxLabel: '启用 GPU (CUDA)',
      },
      {
        key: 'connection_mode',
        label: '连接模式',
        type: 'select',
        defaultValue: 'standalone',
        options: [
          { value: 'standalone', label: 'Standalone' },
          { value: 'editor', label: 'Editor' },
        ],
        description: 'UE5启动方式',
      },
    ],
  },
  {
    id: 'movement',
    name: '移动配置',
    icon: MovementConfigIcon,
    count: 4,
    params: [
      {
        key: 'MoveStepScale',
        label: '前进步长',
        type: 'number',
        defaultValue: 20.0,
        step: 1,
        min: 0,
        description: 'Action[0]=1 时的前进距离',
      },
      {
        key: 'TurnStepDegrees',
        label: '转向角度 (度)',
        type: 'number',
        defaultValue: 15.0,
        step: 1,
        min: 0,
        description: 'Action[1]=1 时的转向角度',
      },
      {
        key: 'ReachTargetDistance',
        label: '到达目标距离阈值',
        type: 'number',
        defaultValue: 50.0,
        step: 1,
        min: 1,
        description: '距离目标小于该值时判定抵达',
      },
      {
        key: 'MaxObserveDistance',
        label: '最大观测距离',
        type: 'number',
        defaultValue: 2000.0,
        step: 10,
        min: 1,
        description: '距离观测归一化上限',
      },
    ],
  },
  {
    id: 'perception',
    name: '感知配置',
    icon: PerceptionConfigIcon,
    count: 5,
    params: [
      {
        key: 'PerceptionHalfExtent',
        label: '感知半宽',
        type: 'number',
        defaultValue: 30.0,
        step: 1,
        min: 0,
        description: '体积 Sweep 的半宽',
      },
      {
        key: 'bUseBoxSweep',
        label: '使用盒体扫描',
        type: 'checkbox',
        defaultValue: true,
        description: '关闭后退化为球体扫描',
        checkboxLabel: '启用盒体扫描',
      },
      {
        key: 'TargetSideClearanceAngleDegrees',
        label: '侧向辅助观测角度',
        type: 'number',
        defaultValue: 30.0,
        step: 1,
        min: 0,
        max: 89,
        description: '目标方向两侧辅助观测射线的偏转角度',
      },
      {
        key: 'bDebugDrawRays',
        label: '绘制射线调试',
        type: 'checkbox',
        defaultValue: false,
        description: '是否绘制射线调试可视化',
        checkboxLabel: '启用射线调试',
      },
      {
        key: 'DebugRayDuration',
        label: '射线显示时长',
        type: 'number',
        defaultValue: 0.0,
        step: 0.1,
        min: 0,
        description: '0 表示仅显示一帧',
      },
    ],
  },
  {
    id: 'reward',
    name: '导航奖励',
    icon: NavigationRewardIcon,
    count: 16,
    params: [
      {
        key: 'MaxSteps',
        label: '最大步数',
        type: 'number',
        defaultValue: 500,
        step: 10,
        min: 1,
        description: '单回合最大步数',
      },
      {
        key: 'DistanceRewardScale',
        label: '距离缩短奖励',
        type: 'number',
        defaultValue: 0.12,
        step: 0.01,
        min: 0,
        description: '距离目标缩短时的奖励缩放',
      },
      {
        key: 'StepPenalty',
        label: '步惩罚',
        type: 'number',
        defaultValue: 0.02,
        step: 0.01,
        min: 0,
        description: '每步固定时间成本',
      },
      {
        key: 'CollisionPenalty',
        label: '碰撞惩罚',
        type: 'number',
        defaultValue: 1.5,
        step: 0.1,
        min: 0,
        description: '发生碰撞时的惩罚',
      },
      {
        key: 'StuckDistanceThreshold',
        label: '停滞距离阈值',
        type: 'number',
        defaultValue: 1.0,
        step: 0.1,
        min: 0,
        description: '单步位移小于该值视为停滞',
      },
      {
        key: 'StuckPenalty',
        label: '停滞惩罚',
        type: 'number',
        defaultValue: 0.2,
        step: 0.01,
        min: 0,
        description: '贴墙停滞惩罚',
      },
      {
        key: 'StuckPenaltyRamp',
        label: '停滞惩罚递增',
        type: 'number',
        defaultValue: 0.05,
        step: 0.01,
        min: 0,
        description: '连续停滞每步额外增加的惩罚',
      },
      {
        key: 'MaxConsecutiveStuckSteps',
        label: '最大连续停滞步数',
        type: 'number',
        defaultValue: 25,
        step: 1,
        min: 1,
        description: '超过后可提前截断',
      },
      {
        key: 'DistanceStuckThreshold',
        label: '目标距离停滞阈值',
        type: 'number',
        defaultValue: 2.0,
        step: 0.1,
        min: 0,
        description: '单步距离改善低于该值视为停滞',
      },
      {
        key: 'MaxDistanceStuckSteps',
        label: '目标距离停滞步数',
        type: 'number',
        defaultValue: 12,
        step: 1,
        min: 1,
        description: '连续多少步未接近目标后开始惩罚',
      },
      {
        key: 'DistanceStuckPenalty',
        label: '目标距离停滞惩罚',
        type: 'number',
        defaultValue: 0.15,
        step: 0.01,
        min: 0,
        description: '目标距离停滞时的基础惩罚',
      },
      {
        key: 'RayOpeningThreshold',
        label: '射线突然打开阈值',
        type: 'number',
        defaultValue: 0.18,
        step: 0.01,
        min: 0,
        description: '射线距离增量超过该值视为方向打开',
      },
      {
        key: 'RaySuddenOpeningReward',
        label: '射线突然打开奖励',
        type: 'number',
        defaultValue: 0.06,
        step: 0.01,
        min: 0,
        description: '某方向突然打开时给予的探索奖励',
      },
      {
        key: 'ClearanceRewardScale',
        label: '通路开阔奖励',
        type: 'number',
        defaultValue: 0.2,
        step: 0.01,
        min: 0,
        description: '目标方向通路变开阔时的奖励',
      },
      {
        key: 'ReachTargetReward',
        label: '到达目标奖励',
        type: 'number',
        defaultValue: 10.0,
        step: 0.5,
        min: 0,
        description: '到达目标的终点奖励',
      },
      {
        key: 'TargetAlignmentRewardScale',
        label: '目标对齐奖励',
        type: 'number',
        defaultValue: 0.08,
        step: 0.01,
        min: 0,
        description: '移动方向与目标方向对齐的奖励',
      },
    ],
  },
  {
    id: 'advanced',
    name: '高级导航奖励',
    icon: AdvancedNavRewardIcon,
    count: 8,
    params: [
      {
        key: 'FacingRewardScale',
        label: '静态朝向奖励',
        type: 'number',
        defaultValue: 0.5,
        step: 0.01,
        min: 0,
        description: '当前朝向与目标方向的静态对齐奖励',
      },
      {
        key: 'FacingImprovementRewardScale',
        label: '朝向改善奖励',
        type: 'number',
        defaultValue: 1.0,
        step: 0.05,
        min: 0,
        description: '当前步朝向改善奖励',
      },
      {
        key: 'HeadingGateExponent',
        label: '朝向门控指数',
        type: 'number',
        defaultValue: 2.0,
        step: 0.1,
        min: 1,
        description: '朝向距离门控指数',
      },
      {
        key: 'BypassRewardScale',
        label: '绕障机会奖励',
        type: 'number',
        defaultValue: 0.35,
        step: 0.01,
        min: 0,
        description: '发现更好侧向通路时的奖励',
      },
      {
        key: 'BypassOpportunityEmaAlpha',
        label: '绕障 EMA 系数',
        type: 'number',
        defaultValue: 0.35,
        step: 0.01,
        min: 0,
        max: 1,
        description: '绕障机会 EMA 平滑系数',
      },
      {
        key: 'TurnSafetyRewardScale',
        label: '转向安全奖励',
        type: 'number',
        defaultValue: 0.6,
        step: 0.01,
        min: 0,
        description: '动作方向安全余量改善奖励',
      },
      {
        key: 'UnsafeActionSafetyThreshold',
        label: '危险动作安全阈值',
        type: 'number',
        defaultValue: 0.3,
        step: 0.01,
        min: 0,
        max: 1,
        description: '前冲时安全余量过低的阈值',
      },
      {
        key: 'BadForwardPenaltyScale',
        label: '盲目前冲惩罚',
        type: 'number',
        defaultValue: 0.35,
        step: 0.01,
        min: 0,
        description: '朝向差或安全余量低时仍前冲的惩罚',
      },
    ],
  },
  {
    id: 'turning',
    name: '原地转向策略',
    icon: TurnInPlateIcon,
    count: 2,
    params: [
      {
        key: 'TurningStepPenaltyScale',
        label: '转向步罚保留比例',
        type: 'number',
        defaultValue: 0.2,
        step: 0.01,
        min: 0,
        max: 1,
        description: '有效原地转向时的步罚保留比例',
      },
      {
        key: 'EffectiveTurnThresholdDegrees',
        label: '有效转角阈值',
        type: 'number',
        defaultValue: 5.0,
        step: 0.5,
        min: 0,
        description: '超过该转角才视为有效原地转向',
      },
    ],
  },
]

export const navigationDefaultParams = {}
navigationParamGroups.forEach((group) => {
  group.params.forEach((param) => {
    navigationDefaultParams[param.key] = param.defaultValue
  })
})
