import TrainingConfigIcon from '@/assets/icons/TrainingConfig.png'
import EnvironmentConfigIcon from '@/assets/icons/EnvironmentConfig.png'
import CurriculumIcon from '@/assets/icons/Curriculum.png'
import CoreRewardIcon from '@/assets/icons/CoreReward.png'
import CommandRewardIcon from '@/assets/icons/CommandReward.png'
import GaitRewardIcon from '@/assets/icons/GaitReward.png'
import RegularizationIcon from '@/assets/icons/Regularization.png'
import TrunkStabilityIcon from '@/assets/icons/TrunkStability.png'
import ActionConfigIcon from '@/assets/icons/ActionConfig.png'
import ObservationConfigIcon from '@/assets/icons/ObservationConfig.png'
import AdvancedDebugIcon from '@/assets/icons/AdvancedDebug.png'

export const orangeRobotParamGroups = [
  {
    id: 'basic',
    name: '基础训练配置',
    icon: TrainingConfigIcon,
    count: 5,
    params: [
      {
        key: 'total_timesteps',
        label: '总训练步数',
        type: 'number',
        defaultValue: 1500000,
        step: 1000,
        min: 1000,
        description: '训练的总步数，影响训练时长和最终效果',
      },
      {
        key: 'learning_rate',
        label: '学习率',
        type: 'number',
        defaultValue: 0.0001,
        step: 0.00001,
        min: 0.000001,
        max: 0.01,
        description: '控制模型参数更新的速度',
      },
      {
        key: 'batch_size',
        label: '批次大小',
        type: 'number',
        defaultValue: 1024,
        step: 32,
        min: 32,
        max: 4096,
        description: '每次训练使用的样本数量',
      },
      {
        key: 'use_gpu',
        label: '使用GPU',
        type: 'checkbox',
        defaultValue: true,
        description: '是否使用GPU加速训练',
        checkboxLabel: '启用 GPU (CUDA)',
      },
      {
        key: 'connection_mode',
        label: '连接模式',
        type: 'select',
        defaultValue: 'standalone',
        options: [
          { value: 'standalone', label: 'Standalone' },
          { value: 'editor', label: 'Editor' },
        ],
        description: 'UE5启动方式',
      },
    ],
  },
  {
    id: 'env',
    name: '环境参数',
    icon: EnvironmentConfigIcon,
    count: 13,
    params: [
      {
        key: 'MaxSteps',
        label: '最大步数',
        type: 'number',
        defaultValue: 2000,
        step: 100,
        min: 100,
        description: '每个episode的最大步数',
      },
      {
        key: 'SimulationFrequencyHz',
        label: '模拟频率 (Hz)',
        type: 'number',
        defaultValue: 30.0,
        step: 1,
        min: 10,
        max: 120,
        description: '物理模拟的频率',
      },
      {
        key: 'FallTiltThreshold',
        label: '倾倒角度阈值 (度)',
        type: 'number',
        defaultValue: 60.0,
        step: 1,
        min: 10,
        max: 90,
        description: '机器人倾斜超过此角度视为倒地',
      },
      {
        key: 'BodyHeightThreshold',
        label: '身体高度阈值 (cm)',
        type: 'number',
        defaultValue: 50.0,
        step: 1,
        min: 10,
        max: 200,
        description: '身体低于此高度（cm）视为倒地，需低于自然站立高度10cm以上',
      },
      {
        key: 'HeadGroundHeightThreshold',
        label: '头部离地高度 (cm)',
        type: 'number',
        defaultValue: 35.0,
        step: 1,
        min: 5,
        max: 100,
        description: '头部低于此高度视为倒地',
      },
      {
        key: 'FallPenaltyHorizon',
        label: '倒地惩罚范围',
        type: 'number',
        defaultValue: 50,
        step: 10,
        min: 10,
        max: 1000,
        description: '倒地前多少步开始施加惩罚',
      },
      {
        key: 'BodyHeightRewardMax',
        label: '最大身体高度奖励 (cm)',
        type: 'number',
        defaultValue: 60.0,
        step: 1,
        min: 10,
        max: 200,
        description: '达到此高度时获得最大奖励',
      },
      {
        key: 'FootSupportTraceDistance',
        label: '足部支撑距离 (cm)',
        type: 'number',
        defaultValue: 12.0,
        step: 0.5,
        min: 1,
        max: 50,
        description: '检测足部接触地面的射线长度',
      },
      {
        key: 'FootStableSpeedThreshold',
        label: '足部稳定速度 (cm/s)',
        type: 'number',
        defaultValue: 35.0,
        step: 1,
        min: 1,
        max: 100,
        description: '足部速度低于此值视为稳定',
      },
      {
        key: 'bEnableCommandReward',
        label: '启用指令跟踪奖励',
        type: 'checkbox',
        defaultValue: true,
        description: '是否启用高层命令跟踪奖励',
        checkboxLabel: '启用命令奖励',
      },
      {
        key: 'bEnableHighLevelCommand',
        label: '启用高层命令接口',
        type: 'checkbox',
        defaultValue: true,
        description: '是否启用高层前进/转向命令接口',
        checkboxLabel: '启用高层命令',
      },
      {
        key: 'MaxForwardSpeed',
        label: '最大前进速度 (cm/s)',
        type: 'number',
        defaultValue: 200.0,
        step: 5,
        min: 0,
        max: 1000,
        description: '高层命令对应的最大前进速度',
      },
      {
        key: 'MaxTurnSpeedDegPerSec',
        label: '最大转向速度 (deg/s)',
        type: 'number',
        defaultValue: 90.0,
        step: 5,
        min: 0,
        max: 720,
        description: '高层命令对应的最大转向速度',
      },
    ],
  },
  {
    id: 'curriculum',
    name: '课程学习',
    icon: CurriculumIcon,
    count: 2,
    params: [
      {
        key: 'bEnableCurriculum',
        label: '启用课程学习',
        type: 'checkbox',
        defaultValue: true,
        description: '是否启用 C++ 侧课程学习权重调度',
        checkboxLabel: '启用课程学习',
      },
      {
        key: 'CurriculumStageBoundaries',
        label: '课程阶段边界',
        type: 'text',
        defaultValue: '300000,450000,750000,1100000',
        description: '课程阶段切换步数，使用逗号分隔',
      },
    ],
  },
  {
    id: 'core',
    name: '核心奖励',
    icon: CoreRewardIcon,
    count: 6,
    params: [
      {
        key: 'AliveReward',
        label: '存活奖励',
        type: 'number',
        defaultValue: 0.06,
        step: 0.001,
        min: 0,
        max: 1,
        description: '每步存活获得的基础奖励',
      },
      {
        key: 'TiltQualityGate',
        label: '存活倾斜门控',
        type: 'number',
        defaultValue: 0.7,
        step: 0.05,
        min: 0.5,
        max: 0.85,
        description: '倾斜超过此门控时当帧存活奖励归零（cos(45°)≈0.7）',
      },
      {
        key: 'HeightRewardScale',
        label: '高度奖励缩放',
        type: 'number',
        defaultValue: 0.20,
        step: 0.001,
        min: 0,
        max: 1,
        description: '身体高度奖励的权重',
      },
      {
        key: 'LateralVelocityPenaltyScale',
        label: '横向速度惩罚',
        type: 'number',
        defaultValue: 0.05,
        step: 0.001,
        min: 0,
        max: 1,
        description: '横向移动的惩罚权重',
      },
      {
        key: 'StableDoubleSupportRewardScale',
        label: '双足支撑奖励',
        type: 'number',
        defaultValue: 0.20,
        step: 0.01,
        min: 0,
        max: 1,
        description: '双足稳定支撑时的奖励',
      },
      {
        key: 'TrunkTiltPenaltyScale',
        label: '躯干倾斜惩罚',
        type: 'number',
        defaultValue: 0.15,
        step: 0.01,
        min: 0,
        max: 1,
        description: '躯干倾斜的惩罚权重',
      },
    ],
  },
  {
    id: 'command',
    name: '指令激励',
    icon: CommandRewardIcon,
    count: 8,
    params: [
      {
        key: 'CommandRewardScale',
        label: '命令奖励总缩放',
        type: 'number',
        defaultValue: 1.0,
        step: 0.1,
        min: 0,
        description: '命令跟踪奖励的总缩放系数',
      },
      {
        key: 'CommandMatchBaseReward',
        label: '完美匹配基础奖励',
        type: 'number',
        defaultValue: 0.5,
        step: 0.05,
        min: 0,
        description: '速度匹配理想时的基础奖励值',
      },
      {
        key: 'ForwardCommandRewardWeight',
        label: '前进命令权重',
        type: 'number',
        defaultValue: 0.7,
        step: 0.05,
        min: 0,
        max: 1,
        description: '前进命令在命令奖励中的权重',
      },
      {
        key: 'TurnCommandRewardWeight',
        label: '转向命令权重',
        type: 'number',
        defaultValue: 0.3,
        step: 0.05,
        min: 0,
        max: 1,
        description: '转向命令在命令奖励中的权重',
      },
      {
        key: 'ForwardCommandMatchSigmaMin',
        label: '前进匹配最小 Sigma',
        type: 'number',
        defaultValue: 25.0,
        step: 1,
        min: 0,
        description: '前进速度匹配奖励的最小 sigma',
      },
      {
        key: 'TurnCommandMatchSigmaMin',
        label: '转向匹配最小 Sigma',
        type: 'number',
        defaultValue: 15.0,
        step: 1,
        min: 0,
        description: '转向速度匹配奖励的最小 sigma',
      },
      {
        key: 'StandCommandSigma',
        label: '站立命令 Sigma',
        type: 'number',
        defaultValue: 15.0,
        step: 1,
        min: 0,
        description: '站立命令时对漂移敏感度的标准差',
      },
      {
        key: 'DynamicBalanceRewardWeight',
        label: '动态平衡总权重',
        type: 'number',
        defaultValue: 1.0,
        step: 0.05,
        min: 0,
        max: 1,
        description: '步态相关奖励的统一混合权重',
      },
    ],
  },
  {
    id: 'gait',
    name: '步态奖励',
    icon: GaitRewardIcon,
    count: 13,
    params: [
      {
        key: 'DualFootShufflePenaltyScale',
        label: '双足拖曳惩罚',
        type: 'number',
        defaultValue: 0.01,
        step: 0.0001,
        min: 0,
        description: '双足同时拖地的惩罚',
      },
      {
        key: 'SwingFootMinHeight',
        label: '摆动足最小高度 (cm)',
        type: 'number',
        defaultValue: 8.0,
        step: 0.5,
        min: 0,
        description: '摆动足应达到的最小高度',
      },
      {
        key: 'SwingFootHeightPenaltyScale',
        label: '摆动足高度惩罚',
        type: 'number',
        defaultValue: 0.01,
        step: 0.001,
        min: 0,
        description: '摆动足高度不足的惩罚',
      },
      {
        key: 'SingleSupportBonusReward',
        label: '单足支撑奖励',
        type: 'number',
        defaultValue: 0.12,
        step: 0.01,
        min: 0,
        description: '单足稳定支撑的奖励',
      },
      {
        key: 'StepAlternationRewardScale',
        label: '步态交替奖励',
        type: 'number',
        defaultValue: 0.1,
        step: 0.01,
        min: 0,
        description: '左右脚交替迈步的奖励',
      },
      {
        key: 'SameLegDominancePenaltyScale',
        label: '同腿主导惩罚',
        type: 'number',
        defaultValue: 0.05,
        step: 0.01,
        min: 0,
        description: '连续使用同一条腿的惩罚',
      },
      {
        key: 'KneeExtensionPenaltyScale',
        label: '膝关节伸展惩罚',
        type: 'number',
        defaultValue: 0.001,
        step: 0.0001,
        min: 0,
        max: 0.01,
        description: '膝关节弯曲的平方惩罚，促进腿伸直行走',
      },
      {
        key: 'GaitSymmetryPenaltyScale',
        label: '步态对称惩罚',
        type: 'number',
        defaultValue: 0.02,
        step: 0.001,
        min: 0,
        description: '左右步态不对称的惩罚',
      },
      {
        key: 'StepFrequencyRewardScale',
        label: '步频奖励',
        type: 'number',
        defaultValue: 0.1,
        step: 0.01,
        min: 0,
        description: '合理步频的奖励',
      },
      {
        key: 'MinStepFrequencyHz',
        label: '最小步频 (Hz)',
        type: 'number',
        defaultValue: 1.0,
        step: 0.1,
        min: 0.1,
        description: '期望的最小步频',
      },
      {
        key: 'MaxStepFrequencyHz',
        label: '最大步频 (Hz)',
        type: 'number',
        defaultValue: 3.0,
        step: 0.1,
        min: 0.5,
        description: '期望的最大步频',
      },
      {
        key: 'FootImpactPenaltyScale',
        label: '足部冲击惩罚',
        type: 'number',
        defaultValue: 0.01,
        step: 0.001,
        min: 0,
        description: '足部着地冲击过大的惩罚',
      },
      {
        key: 'FootImpactVelocityThreshold',
        label: '足部冲击速度阈值 (cm/s)',
        type: 'number',
        defaultValue: 50.0,
        step: 5,
        min: 10,
        description: '超过此速度视为冲击过大',
      },
    ],
  },
  {
    id: 'regularization',
    name: '正则化',
    icon: RegularizationIcon,
    count: 5,
    params: [
      {
        key: 'ActionSmoothPenaltyScale',
        label: '动作平滑惩罚',
        type: 'number',
        defaultValue: 0.008,
        step: 0.001,
        min: 0,
        description: '动作变化过快的惩罚',
      },
      {
        key: 'ActionMagnitudePenaltyScale',
        label: '动作幅度惩罚',
        type: 'number',
        defaultValue: 0.005,
        step: 0.001,
        min: 0,
        description: '动作幅度过大的惩罚',
      },
      {
        key: 'EnergySigma',
        label: '能量消耗 Sigma',
        type: 'number',
        defaultValue: 0.5,
        step: 0.1,
        min: 0.1,
        description: '能量消耗的标准差参数',
      },
      {
        key: 'CostOfTransportScale',
        label: '运输成本缩放',
        type: 'number',
        defaultValue: 0.003,
        step: 0.001,
        min: 0,
        description: '运输成本的惩罚权重',
      },
      {
        key: 'ForwardSpeedRewardMax',
        label: '前向速度归一化上限 (cm/s)',
        type: 'number',
        defaultValue: 150.0,
        step: 5,
        min: 1,
        description: '运输成本归一化依赖的最大前向速度',
      },
    ],
  },
  {
    id: 'trunk',
    name: '躯干稳定性',
    icon: TrunkStabilityIcon,
    count: 7,
    params: [
      {
        key: 'TrunkSupportOffsetPenaltyScale',
        label: '躯干支撑偏移惩罚',
        type: 'number',
        defaultValue: 0.003,
        step: 0.001,
        min: 0,
        description: '躯干偏离支撑点的惩罚',
      },
      {
        key: 'TrunkSupportOffsetNormalizeDistance',
        label: '归一化距离 (cm)',
        type: 'number',
        defaultValue: 25.0,
        step: 1,
        min: 5,
        description: '躯干偏移归一化的距离',
      },
      {
        key: 'TrunkAngVelXYPenaltyScale',
        label: '角速度XY惩罚',
        type: 'number',
        defaultValue: 0.00002,
        step: 0.00001,
        min: 0,
        description: '躯干XY平面角速度的惩罚',
      },
      {
        key: 'TrunkVerticalVelocityPenaltyScale',
        label: '垂直速度惩罚',
        type: 'number',
        defaultValue: 0.00001,
        step: 0.00001,
        min: 0,
        description: '躯干垂直速度的惩罚',
      },
      {
        key: 'TrunkVerticalVelocityDeadzone',
        label: '垂直速度死区 (cm/s)',
        type: 'number',
        defaultValue: 5.0,
        step: 0.5,
        min: 0,
        description: '低于此速度不施加惩罚',
      },
      {
        key: 'TiltWarningScale',
        label: '倾倒预警强度',
        type: 'number',
        defaultValue: 1.0,
        step: 0.1,
        min: 0,
        max: 5.0,
        description: '接近倾倒时（超过倒地角度50%）的预警信号强度',
      },
      {
        key: 'HeightDropPenaltyScale',
        label: '高度下降惩罚',
        type: 'number',
        defaultValue: 1.5,
        step: 0.1,
        min: 0,
        description: '身体高度快速下降的惩罚',
      },
    ],
  },
  {
    id: 'action',
    name: '动作配置',
    icon: ActionConfigIcon,
    count: 5,
    params: [
      {
        key: 'ActionDeadzone',
        label: '动作死区',
        type: 'number',
        defaultValue: 0.05,
        step: 0.01,
        min: 0,
        max: 0.5,
        description: '小于此值的动作被忽略',
      },
      {
        key: 'ActionResponseExponent',
        label: '动作响应指数',
        type: 'number',
        defaultValue: 2.0,
        step: 0.1,
        min: 1,
        max: 5,
        description: '动作响应的非线性程度',
      },
      {
        key: 'JointVelocityScale',
        label: '关节速度缩放',
        type: 'number',
        defaultValue: 90.0,
        step: 5,
        min: 10,
        max: 200,
        description: '关节速度的缩放系数',
      },
      {
        key: 'TwistVelocityLimit',
        label: '扭转速度限制 (度/s)',
        type: 'number',
        defaultValue: 60.0,
        step: 5,
        min: 10,
        max: 180,
        description: '关节扭转的最大速度',
      },
      {
        key: 'SwingVelocityLimit',
        label: '摆动速度限制 (度/s)',
        type: 'number',
        defaultValue: 60.0,
        step: 5,
        min: 10,
        max: 180,
        description: '关节摆动的最大速度',
      },
    ],
  },
  {
    id: 'observation',
    name: '观测配置',
    icon: ObservationConfigIcon,
    count: 2,
    params: [
      {
        key: 'TrunkHeightNormalization',
        label: '躯干高度归一化 (cm)',
        type: 'number',
        defaultValue: 100.0,
        step: 5,
        min: 10,
        description: '躯干高度的归一化系数',
      },
      {
        key: 'DesiredStepPeriod',
        label: '期望步态周期 (s)',
        type: 'number',
        defaultValue: 0.5,
        step: 0.05,
        min: 0.1,
        max: 2.0,
        description: '期望的步态周期时间',
      },
    ],
  },
  {
    id: 'advanced',
    name: '高级调试',
    icon: AdvancedDebugIcon,
    count: 5,
    params: [
      {
        key: 'RewardMaskCore',
        label: '核心奖励掩码',
        type: 'number',
        defaultValue: -1,
        step: 1,
        description: '核心奖励组位掩码，-1 表示全部启用',
      },
      {
        key: 'RewardMaskGait',
        label: '步态奖励掩码',
        type: 'number',
        defaultValue: -1,
        step: 1,
        description: '步态奖励组位掩码，-1 表示全部启用',
      },
      {
        key: 'RewardMaskReg',
        label: '正则化奖励掩码',
        type: 'number',
        defaultValue: -1,
        step: 1,
        description: '正则化奖励组位掩码，-1 表示全部启用',
      },
      {
        key: 'bLogRewardBreakdown',
        label: '输出奖励分解日志',
        type: 'checkbox',
        defaultValue: true,
        description: '是否在日志中打印奖励分解',
        checkboxLabel: '启用奖励分解日志',
      },
      {
        key: 'bApplyRandomJointOffsetsOnReset',
        label: '重置时随机关节扰动',
        type: 'checkbox',
        defaultValue: false,
        description: '是否在 Reset 时为关节施加随机速度扰动',
        checkboxLabel: '启用随机扰动',
      },
    ],
  },
]

export const orangeRobotDefaultParams = {}
orangeRobotParamGroups.forEach((group) => {
  group.params.forEach((param) => {
    orangeRobotDefaultParams[param.key] = param.defaultValue
  })
})
